### ISSUE TITLE
please don't mix in-line php code with classes

### ISSUE THREAD

**Issue by danmarsden** [lavanyamanne2/moodle-local_scormcreator#7]
It's much cleaner to put your classes into standalone files within the classes directory - and use our autoloading process to load the class so you don't need to add require_once() style calls to include your classes where you want to use them..

for example - this class:
https://github.com/lavanyamanne2/scormcreator/blob/main/dissolve.php#L61

some more info on autoloading classes in moodle is in the older moodledocs site here:
https://docs.moodle.org/dev/Automatic_class_loading

**Comment by danmarsden** [comment]
another good example that should be moved into it's own class file:
https://github.com/lavanyamanne2/scormcreator/blob/main/manifest.php#L60

**Comment by lavanyamanne2** [comment]
Corrected the class code

**Comment by danmarsden** [comment]
looks like this is is still an issue - perhaps you don't understand? - here's a "php file" to show you as an example:
```
<?php
// This is an example of in-line php code.
echo "1234"'

// this is a function mixed in with the inline code.
function dothis () {
    echo "do this";
}

// Here's some more in-line php code
echo "1234";

// here's a class inside the same file.
class testclass extends moodleform {
    public function definition() {
    }
}
```

Several of your files do this - they have inline code, and classes or functions in the same file - you should move the "classes" into their own standalone file (one file per class).

**Comment by lavanyamanne2** [comment]
Dan Marsden,

Sorry, It doesn't mean I didn't understand.
I didn't find the mix of inline php code, functions and classes. I was done these corrections in my first and second update with your guidance.

I've prechecked all the 19 PHP files:
manifest.php - has one class initialization **local_scormcreator_manifest_form** 
pagecontext.php - has one class class initialization **local_scormcreator_pagecontext_form**
quizcontext.php - has one class class initialization **local_scormcreator_quizcontext_form**
publish.php - there is no custom echo in this page.
edit/editmanifest.php - has one class initialization **local_scormcreator_editmanifest_form**
edit/editpage.php - has one class initialization **local_scormcreator_editpage_form**
edit/editquiz.php - has one class initialization **local_scormcreator_editquiz_form**
edit/editscorm.php - there is no custom echo in this page.
dscorm.php - there is no custom echo in this page.
dissolve.php - there is no custom echo and with only with one function **local_scormcreator_cleanscorm**
classes/lib.php - has one class initialization **local_scormcreator_pluginfile**
classes/locallib.php - has one class initialization **local_scormcreator_scormlib**
classes/privacy/provider - No custom echo's and functions in this page.
db/access.php - no custom echo's and functions.
db/install.xml - only xml code is written.
lang/en/local_scormcreator.php - only language strings.
settings.php - no custom echo's found in this page.
version.php - no custom echo's found in this page.
README.md - only text found.

I didn't find a mix of code (inline php, functions and classes). Please make sure you're referring to the updated plugin code or older code?

**Comment by lavanyamanne2** [comment]
I corrected the custom php code to a single class. Let me know if still things has to be corrected.

**Comment by danmarsden** [comment]
looks like this is still an issue? - dissolve.php contains a mix of inline php and functions?

**Comment by danmarsden** [comment]
manifest_form contains inline code and a class...

**Comment by danmarsden** [comment]
pagecontext_form.php too...

**Comment by danmarsden** [comment]
publish.php, quizcontext_form.php too

**Comment by danmarsden** [comment]
bunch of files in /edit/ that do it too..

**Comment by lavanyamanne2** [comment]
Solved
